version: "3"
services:
  reserva:
    image: joaogabrielcampos/gestao-reserva:latest
    ports:
      - "8082:8082"
    networks:
      - hospitalidade
    depends_on:
      - customer
      - options
      - quarto

  customer:
    image: joaogabrielcampos/customer-management:latest
    ports:
      - "8083:8083"
    networks:
      - hospitalidade

  options:
    image: joaogabrielcampos/service-and-options-management:latest
    ports:
      - "8084:8084"
    networks:
      - hospitalidade

  quarto:
    image: joaogabrielcampos/gestao-quarto:latest
    ports:
      - "8081:8081"
    networks:
      - hospitalidade

networks:
  hospitalidade: